"adicionando scripts"

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,35 +1,49 @@
 steps:
-# Passo 1: Clonar a branch de desenvolvimento do repositório
+# Passo 1: Clonar o repositório (caso necessário)
 - name: 'gcr.io/cloud-builders/git'
-  args: ['clone', '--branch=develop', 'https://github.com/GabrielPerosa/Pipeline-Dataform.git']
+  args: ['clone', 'https://github.com/GabrielPerosa/Pipeline-Dataform.git']
 
-# Passo 2: Instalar a ferramenta SQLFluff para verificação de qualidade do código SQL
+# Passo 2: Instalar dependências do SQLFluff
 - name: 'python:3.9'
   entrypoint: 'bash'
-  args:
-    - '-c'
-    - |
-      pip install sqlfluff
+  script: |
+    pip install --no-cache-dir sqlfluff
 
-# Passo 3: Executar o SQLFluff nos arquivos SQL
+# Passo 3: Verificar qualidade dos scripts SQL
 - name: 'python:3.9'
   entrypoint: 'bash'
-  args:
-    - '-c'
-    - |
-      sqlfluff lint /workspace --dialect bigquery
+  script: |
+    # Identificar o email do autor do commit
+    COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
+    # Executar o lint nos scripts dentro do diretório 'definitions'
+    sqlfluff lint definitions/*.sqlx > lint-results.txt
+    # Verificar o resultado do lint
+    if grep -q "L:  " lint-results.txt; then
+      echo "Testes SQL falharam. Notificando erro por email."
+      echo "SQL Quality Check Failed. Review the errors in lint-results.txt." | mail -s "SQL Lint Failure" $COMMIT_AUTHOR_EMAIL
+      exit 1
+    else
+      echo "SQL Quality Check Passed."
+    fi
 
-# Passo 4: Validar o resultado do lint e condicionar as ações
+# Passo 4: Mesclar na branch main caso os testes passem
 - name: 'gcr.io/cloud-builders/git'
   entrypoint: 'bash'
-  args:
-    - '-c'
-    - |
-      if sqlfluff lint /workspace --dialect bigquery | grep -q "FAIL"; then
-        echo "Qualidade do código não foi aprovada. Notificando falha."
-        exit 1
-      else
-        git checkout main
-        git merge develop
-        git push origin main
-      fi
+  script: |
+    git checkout main
+    git merge develop
+    git push origin main
+
+# Passo 5: Enviar scripts para o Dataform
+- name: 'gcr.io/cloud-builders/gcloud'
+  args: [
+    'dataform', 'install',
+    '--repository="repositorio-producao"',
+    '--workspace="workspace-dataform-produca"',
+    '--location="southamerica-east1"'
+  ]
+
+substitutions:
+  _COMMIT_AUTHOR_EMAIL: 'default@example.com'
+
+timeout: '1200s'
